
name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: ... build success ...
        run: echo ... build success ...

      - name: ... check node version ...
        run: node -v 

  tests:
    name: Tests
    runs-on: self-hosted
    steps:

      - name: ... tests success ...
        run: echo ... tests success ...

  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:

      - name: ... deploy success ...
        run: echo ... deploy success ...

  cleanUp:
    name: Clean up
    runs-on: self-hosted
    steps:
      
      - name: ... clean up success ...
        run: echo ... clean up success ...
